export const TYPOGRAPHY_TEMPLATES = [
  {
    id: 'cinematic-minimal',
    name: 'Cinematic Minimal',
    description: 'Thin elegant serif title with wide spaced italic caption. Perfect for films, documentaries, and cinematic vlogs.',
    animation: 'blur-slide',
    duration: 4.5,
    lines: [
      {
        text: 'E T H E R E A L',
        font: 'Cinzel',
        size: 64,
        weight: '300',
        italic: false,
        transform: 'uppercase',
        color: '#ffffff',
        tracking: 10,
        glow: false,
        glowColor: '#ffffff',
        glowSize: 0,
        shadow: true,
        shadowColor: 'rgba(0, 0, 0, 0.5)',
        shadowBlur: 8,
        shadowX: 0,
        shadowY: 4
      },
      {
        text: 'A Journey Through the Void',
        font: 'Cormorant Garamond',
        size: 32,
        weight: '300',
        italic: true,
        transform: 'none',
        color: '#94a3b8',
        tracking: 2,
        glow: false,
        glowColor: '',
        glowSize: 0,
        shadow: true,
        shadowColor: 'rgba(0, 0, 0, 0.4)',
        shadowBlur: 4,
        shadowX: 0,
        shadowY: 2
      }
    ]
  },
  {
    id: 'cyber-neon',
    name: 'Cyber Neon',
    description: 'Vibrant cyberpunk styling with heavy glowing text effects and chromatic glitch vibrations. High impact.',
    animation: 'cyber-glitch',
    duration: 4.0,
    lines: [
      {
        text: 'SYSTEM BOOT',
        font: 'Space Grotesk',
        size: 72,
        weight: '700',
        italic: false,
        transform: 'uppercase',
        color: '#06b6d4',
        tracking: 4,
        glow: true,
        glowColor: '#06b6d4',
        glowSize: 20,
        shadow: true,
        shadowColor: '#0891b2',
        shadowBlur: 10,
        shadowX: 0,
        shadowY: 0
      },
      {
        text: 'SECTOR DECRYPTION IN PROGRESS',
        font: 'Space Grotesk',
        size: 20,
        weight: '500',
        italic: false,
        transform: 'uppercase',
        color: '#ffffff',
        tracking: 8,
        glow: true,
        glowColor: '#8b5cf6',
        glowSize: 10,
        shadow: false,
        shadowColor: '',
        shadowBlur: 0,
        shadowX: 0,
        shadowY: 0
      }
    ]
  },
  {
    id: 'vogue-editorial',
    name: 'Vogue Editorial',
    description: 'Ultra high-contrast fashion editorial typography with dramatic italicized serif and wide letter spacing.',
    animation: 'typewriter',
    duration: 5.0,
    lines: [
      {
        text: 'Couture',
        font: 'Bodoni Moda',
        size: 84,
        weight: '800',
        italic: true,
        transform: 'none',
        color: '#ffffff',
        tracking: 0,
        glow: false,
        glowColor: '',
        glowSize: 0,
        shadow: true,
        shadowColor: 'rgba(0, 0, 0, 0.3)',
        shadowBlur: 6,
        shadowX: 2,
        shadowY: 3
      },
      {
        text: 'AUTUMN / WINTER COLLECTION',
        font: 'Prata',
        size: 18,
        weight: '400',
        italic: false,
        transform: 'uppercase',
        color: '#cbd5e1',
        tracking: 12,
        glow: false,
        glowColor: '',
        glowSize: 0,
        shadow: true,
        shadowColor: 'rgba(0, 0, 0, 0.4)',
        shadowBlur: 4,
        shadowX: 0,
        shadowY: 2
      }
    ]
  },
  {
    id: 'bold-kinetic',
    name: 'Bold Kinetic',
    description: 'Impactful, ultra-heavy display typography designed to slam in with cushions. Great for sports, promos, and dynamic edits.',
    animation: 'cushion-bounce',
    duration: 3.5,
    lines: [
      {
        text: 'LIMITLESS',
        font: 'Outfit',
        size: 96,
        weight: '900',
        italic: false,
        transform: 'uppercase',
        color: '#ffffff',
        tracking: -2,
        glow: false,
        glowColor: '',
        glowSize: 0,
        shadow: true,
        shadowColor: 'rgba(0, 0, 0, 0.6)',
        shadowBlur: 12,
        shadowX: 4,
        shadowY: 8
      },
      {
        text: 'BREAKING ALL BOUNDARIES',
        font: 'Space Grotesk',
        size: 26,
        weight: '700',
        italic: false,
        transform: 'uppercase',
        color: '#a78bfa',
        tracking: 6,
        glow: true,
        glowColor: '#8b5cf6',
        glowSize: 8,
        shadow: true,
        shadowColor: 'rgba(0,0,0,0.5)',
        shadowBlur: 4,
        shadowX: 0,
        shadowY: 2
      }
    ]
  },
  {
    id: 'modern-minimalist',
    name: 'Modern Clean',
    description: 'Ultra-clean sans-serif layout. Perfect for product vlogs, tutorials, technology showcases, and corporate clips.',
    animation: 'blur-slide',
    duration: 4.0,
    lines: [
      {
        text: 'Design Systems',
        font: 'Outfit',
        size: 58,
        weight: '600',
        italic: false,
        transform: 'none',
        color: '#f8fafc',
        tracking: -1,
        glow: false,
        glowColor: '',
        glowSize: 0,
        shadow: true,
        shadowColor: 'rgba(0, 0, 0, 0.4)',
        shadowBlur: 6,
        shadowX: 0,
        shadowY: 2
      },
      {
        text: 'Building structured visual layouts',
        font: 'Inter',
        size: 24,
        weight: '300',
        italic: false,
        transform: 'none',
        color: '#64748b',
        tracking: 1,
        glow: false,
        glowColor: '',
        glowSize: 0,
        shadow: false,
        shadowColor: '',
        shadowBlur: 0,
        shadowX: 0,
        shadowY: 0
      }
    ]
  },
  {
    id: 'retro-arcade',
    name: 'Retro Arcade',
    description: 'Chunky 8-bit gaming title with flashing green and orange glows. Great for retro reviews and gaming streams.',
    animation: 'typewriter',
    duration: 4.0,
    lines: [
      {
        text: 'LEVEL COMPLETED',
        font: 'Press Start 2P',
        size: 32,
        weight: '400',
        italic: false,
        transform: 'uppercase',
        color: '#f59e0b',
        tracking: 4,
        glow: true,
        glowColor: '#f59e0b',
        glowSize: 12,
        shadow: true,
        shadowColor: '#000000',
        shadowBlur: 4,
        shadowX: 4,
        shadowY: 4
      },
      {
        text: 'SCORE: 198000 PTS',
        font: 'Press Start 2P',
        size: 16,
        weight: '400',
        italic: false,
        transform: 'uppercase',
        color: '#10b981',
        tracking: 2,
        glow: true,
        glowColor: '#10b981',
        glowSize: 8,
        shadow: true,
        shadowColor: '#000000',
        shadowBlur: 2,
        shadowX: 2,
        shadowY: 2
      }
    ]
  },
  {
    id: 'crt-warning',
    name: 'Retro CRT Warning',
    description: 'Vintage monitor warning screen. Heavy horizontal scanlines, screen noise grain, dynamic phosphorus flicker, and alert symbol.',
    animation: 'cyber-glitch',
    duration: 5.0,
    bgType: 'color',
    bgColor: '#07080e',
    crtScanlines: 'horizontal',
    crtScanlineOpacity: 0.45,
    crtScanlineSpacing: 3,
    crtAberration: 4,
    crtFlicker: true,
    crtVignette: true,
    crtNoise: true,
    lines: [
      {
        text: 'WARNING',
        font: 'Outfit',
        size: 84,
        weight: '900',
        italic: false,
        transform: 'uppercase',
        color: '#fca5a5',
        tracking: 2,
        glow: false,
        glowColor: '',
        glowSize: 0,
        shadow: true,
        shadowColor: '#ef4444',
        shadowBlur: 10,
        shadowX: 3,
        shadowY: 3
      },
      {
        text: '[ALERT]',
        font: 'Outfit',
        size: 90,
        weight: '900',
        italic: false,
        transform: 'uppercase',
        color: '#fca5a5',
        tracking: 0,
        glow: false,
        glowColor: '',
        glowSize: 0,
        shadow: true,
        shadowColor: '#ef4444',
        shadowBlur: 10,
        shadowX: 3,
        shadowY: 3
      }
    ]
  },
  {
    id: 'crt-blue-system',
    name: 'CRT System Terminal',
    description: 'Vintage blue terminal screen. Bright blue screen, severe vertical raster scanlines, and intense cyan glowing text.',
    animation: 'cyber-glitch',
    duration: 4.5,
    bgType: 'color',
    bgColor: '#0000ff',
    crtScanlines: 'vertical',
    crtScanlineOpacity: 0.55,
    crtScanlineSpacing: 3,
    crtAberration: 2,
    crtFlicker: true,
    crtVignette: true,
    crtNoise: false,
    lines: [
      {
        text: 'System',
        font: 'Outfit',
        size: 84,
        weight: '800',
        italic: true,
        transform: 'none',
        color: '#ffffff',
        tracking: -2,
        glow: true,
        glowColor: '#38bdf8',
        glowSize: 20,
        shadow: false,
        shadowColor: '',
        shadowBlur: 0,
        shadowX: 0,
        shadowY: 0
      }
    ]
  }
];
